### ISSUE TITLE
Onderscheid overleden personen met en zonder onderliggend lijden

### ISSUE THREAD

**Issue by Sebastix** [mzelst/covid-19#13]
Het CDC maakt hier ook een duidelijk onderscheid in.
https://www.cdc.gov/nchs/nvss/vsrr/covid_weekly/index.htm#Comorbidities

Met dit onderscheid kun je vervolgens ook de leeftijden tonen in beide groepen.

Persoonlijk vind ik dat je dan meer context verwerkt in je data rapportages. Zeker als het zo'n maatschappelijk beladen onderwerp is.

**Comment by mzelst** [comment]
Hi Sebastix,

Dank voor je bericht. Het aantal comorbiditeiten staat niet in de open data van het RIVM, dus die kunnen we helaas niet verwerken in onze rapportages. Het RIVM meldt zelf in haar wekelijkse rapportage overigens wel een overzicht van comorbiditeiten: die kun je op de website van het RIVM vinden. 

Kan ik het issue hiermee sluiten?

Marino

**Comment by Sebastix** [comment]
Hoi Marino,

Het wordt wekelijks gedeeld inderdaad, met die rapportages ben ik bekend (https://www.rivm.nl/documenten?search=Epidemiologische%20situatie%20COVID-19%20in%20Nederland&document_type=All&onderwerp=&page=0%2C0%2C0). Daar staan de cijfers van onderliggende aandoeningen vermeld bij overleden personen onder de 70 jaar (er is ook nog een grote groep boven die leeftijd).
Kan me niet voorstellen dat toch ergens die informatie als ruwe data op te halen is. Het RIVM heeft de data, misschien moet je ze eens bellen?
Hetzelfde geldt namelijk ook voor ziekenhuisopnames. Ook daar werden (dat is op een zeker moment verdwenen in de rapportages) de onderliggende aandoeningen vermeld.

Is het idee om je netwerk (Twitter) eens te vragen naar ruwe data bronnen met deze informatie? Wellicht is er iemand al mee bezig geweest om deze data over te nemen uit de rapportages en ze publiekelijk toegankelijk te maken.

**Comment by mzelst** [comment]
Die ruwe data is op dit moment niet publiekelijk beschikbaar. Bij NICE worden de comorbiditeiten wel meegenomen in de wekelijkse rapportage over de IC die al zeer inzichtelijk is. 

Mocht je de databronnen vinden of kunnen achterhalen, houden we ons uiteraard aanbevolen en zien we die data graag tegemoet.

**Comment by Sebastix** [comment]
Heb je toevallig een url naar die NICE rapportages?

Heb nog geen databronnen kunnen vinden helaas, dus ik zit er aan te denken om deze zelf te gaan opzetten.

**Comment by mzelst** [comment]
Dat rapport kun je op www.stichting-nice.nl vinden onder deze url: https://stichting-nice.nl/COVID_rapport_20201012.pdf
