### ISSUE TITLE
Age groups of 5 instead of 10 years

### ISSUE THREAD

**Issue by EwoutH** [mzelst/covid-19#14]
Would it be possible to split out the age groups in sections of 5 years instead of 10 years? So 0-4 and 5-9 instead of 0-9, etc.?

Especially for 10-14 and 15-19, and 20-24 and 25-29 there are big differences.

**Comment by mzelst** [comment]
Unfortunately, that will only be possible if the raw data is supplied in such a way. Currently, the RIVM supplies the case data in 10 year intervals and I have no knowledge of any plans to change that in the nearby future.
