### ISSUE TITLE
all_data.csv aantal kolommen aangepast met de commit van vandaag

### ISSUE THREAD

**Issue by sonar98** [mzelst/covid-19#20]
Hoi Marino,

Ten eerste bedankt voor al je werk in deze repository.
Met plezier gebruiken we jouw dataset uit de all_data.csv voor een dashboard.
Nu valt me op dat af en toe de structuur van dit bestand aangepast wordt waardoor ons dashboard de data niet meer goed kan verwerken.
Ik snap dat je de data primair voor je eigen overzichten klaar zet maar persoonlijk zou ik het erg fijn vinden als deze structuur niet te vaak aangepast wordt.

Sinds vandaag is bijvoorbeeld de kolom X.1 ineens niet meer beschikbaar. 
Is er een reden waarom deze kolom er niet meer is? En zijn dit soort wijzigingen vaker te verwachten?

Groeten,
Maarten

**Comment by edwinveldhuizen** [comment]
Hi Maarten,

Dat was denk ik mijn fout toen ik LCPS heb toegevoegd. Bij deze tabel heb ik er niet rekening mee gehouden dat die ook door andere gebruikt wordt, voornamelijk omdat er toch geen mooie kolom namen werden gebruikt 😉 
Welke kolommen gebruik je precies?

Misschien dat we ze dan gewoon een nette consistente naam kunnen geven.
En heb je een linkje naar je dashboard?

Met vriendelijke groet,

Edwin

**Comment by mzelst** [comment]
Hi Maarten,

Nu we klaar zijn met het schrijven van alle benodigde code, ben ik aan een cleanup begonnen. Kolommen die op geen manier inhoudelijk iets aanvulden (zoals de X.x kolommen, die door merges veroorzaakt werden). Ik ben er nu compleet doorheen, dus je zou geen wijzigingen meer moeten zien op dat vlak. Het kan wel zijn dat we over tijd kolommen toe blijven voegen (vanwege nieuwe data), maar de kolomnamen zoals nu gebruikt zullen we zo laten (in verband met pull issues, zoals die van jou).

Ik ben ook benieuwd naar het dashboard waar jullie deze data voor gebruiken!

Met vriendelijke groet,
Marino

**Comment by sonar98** [comment]
Hoi Edwin en Marino,

Bedankt voor de terugkoppeling. Helaas kan ik het dashboard niet laten zien omdat deze alleen voor intern gebruik is.
De basis voor ons interne dashboard is het dashboard van Emiel en Mathijs -> https://www.coviddashboard.nl/

Met vriendelijke groet,
Maarten
