### ISSUE TITLE
Eemsdelta en Haaren

### ISSUE THREAD

**Issue by rikstrijker** [mzelst/covid-19#21]
In the province of Groningen three municipalities merged: Appingedam, Delfzijl and Loppersum. Since the first of January 2021 the new municipality is called Eemsdelta.

In `reports/daily_report.pdf` the figures: `reports/daily_report_files/figure-latex/Gemeentes - Sinds vorige week-1.` and `reports/daily_report_files/figure-latex/Gemeentes - sinds gisteren-1. ` the municipalities Appingedam, Delfzijl and Loppersum are still separate municipalities. \
For `reports/daily_report_files/figure-latex/Gemeentes - Sinds vorige week-1.` one can argue whether it should be  Eemsdelta or Appingedam, Delfzijl and Loppersum, because 2021 is over 3,5 days old, the average should give Eemsdelta :-p

I have no experience with R so can't find how to merge the data of the three municipalities into a new municipality.

According to Wikipedia there is a simulare issue in Noord-Braband with  Haaren: [Gemeentelijke herindelingen](https://nl.wikipedia.org/wiki/Gemeentelijke_herindelingen_in_Nederland#Herindeling_1_januari_2021)
I think Haaren is still visible in the images?

**Comment by mzelst** [comment]
Hi Rik,

Thanks for the comment! We're actively tracking this issue to make this happen, but the CBS data is not in yet for the new municipality of Eemsdelta and the municipality of Haaren is even more difficult (it's divided over multiple other municipalities). The RIVM also is still reporting case data for the 'old' municipalities, implying we can't switch to the new ones until the RIVM changes this in their datasets. They are working on this issue, but it's unclear when they will make the switch. As soon as they change the municipalities, we'll make the switch as well :) 

Marino

**Comment by rikstrijker** [comment]
Oke thanks, hope they will update the data soon, the merge shouldn't come as a surprise, the plans are older as covid...

**Comment by zwakhall** [comment]
RIVM is planning to switch to 2021-municipalities on January 7th. 2021.

**Comment by mzelst** [comment]
@zwakhall Good to know, so we can make the switch on time (tomorrow then). Thanks for the heads-up!
