### ISSUE TITLE
Calculate daily positive test rate from values.tested_total and values.infected for higher precision

### ISSUE THREAD

**Issue by EwoutH** [mzelst/covid-19#22]
First of all, thanks for the amazing work done daily!

Currently `values.infected_percentage` in [data-dashboards/percentage-positive-daily-national.csv](https://github.com/mzelst/covid-19/blob/master/data-dashboards/percentage-positive-daily-national.csv) is rounded to one decimal. With the high infections rates currently not a big problem, but once we (hopefully ever) go back to the <2% rate the decrease in precision is quite significant.

For the plots it would be better to calculate them from the source data, so `values.infected` / `values.tested_total` (and `* 100` for percents).

**Comment by mzelst** [comment]
Hi Ewout,

You're welcome :) 

I agree that more precision would be better (including calculation from source). I will update that next week (it's in the workflow schedule) but given limited time this week, I focused on getting the data out in a usable form for now. Will get back to it!

Marino
