### ISSUE TITLE
data/all_data.csv has wrong date for entry 2020-07-01

### ISSUE THREAD

**Issue by boisei0** [mzelst/covid-19#41]
Hi all,

Spotted this last night, figured out the source only now. In the data/all_data.csv there's 2 entries for 2020-07-02. The first of those entries is actually for 2020-07-01. Since all_data.csv is generated from the daily RIVM files, the source for this can be seen in the individual case files per day:
https://github.com/mzelst/covid-19/blob/6f38e2fd5f2620deba5821cd2064eae8746e0b91/data-rivm/data-per-day/rivm_daily_2020-07-01.csv#L2

While the file name is correct, the date for this entry is listed as 2020-07-02. 

Kind regards,

**Comment by mzelst** [comment]
Consider it fixed!
