### ISSUE TITLE
covid-19/data-rivm/casus-datasets/ not complete

### ISSUE THREAD

**Issue by mckeuken** [mzelst/covid-19#43]
"https://github.com/mzelst/covid-19/raw/master/data-rivm/casus-datasets/COVID-19_casus_landelijk_2022-01-20.csv.gz" seems to be missing from the dataset.

**Comment by mzelst** [comment]
Hi Max, thanks for bringing that to my attention. I just realized that too! I'm gonna have to do some digging to find it somewhere else. If I manage to, I'll be sure to upload it into the repository.

Marino

**Comment by mzelst** [comment]
@mckeuken I have retrieved the original from that day and added it to the repository, which is now once again fully complete. Thank you for bringing this to my attention.

Kind regards,
Marino
